[package]
name = "timed-automata-analyzer"
version = "0.1.0"
authors = ["luth1um <52032867+luth1um@users.noreply.github.com>"]
description = "An analyzer for Timed Automata written in Rust"
license = "MIT"
repository = "https://github.com/luth1um/ta-analyzer"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
