name: CI pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: "24"
  BUILD_ARTIFACT_NAME: "ta-analyzer-build-output"
  BUILD_ARTIFACT_FOLDER: "pkg"
  WASM_TEST_FOLDER: "wasm_test"

jobs:
  # Check linting and formatting
  static-analysis:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable # "stable" sets up the latest stable Rust version
        with:
          components: rustfmt, clippy

      - name: Cache Cargo registry
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #v5.0.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Linting with Cargo check
        run: RUSTFLAGS="-D warnings" cargo check

      - name: Linting with Clippy
        run: cargo clippy -- -D warnings

      - name: Set up Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "${{ env.WASM_TEST_FOLDER }}/package-lock.json"

      - name: Check formatting of the TypeScript test code
        run: |
          cd "${{ env.WASM_TEST_FOLDER }}"
          npm ci
          npx prettier --check .

  # Build the project
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable # "stable" sets up the latest stable Rust version

      - name: Cache Cargo registry
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #v5.0.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache wasm-pack
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #v5.0.4
        with:
          path: ~/.cargo/bin/wasm-pack
          key: ${{ runner.os }}-wasm-pack-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wasm-pack
        run: |
          if [[ ! -f ~/.cargo/bin/wasm-pack ]]; then
            cargo install wasm-pack
          else
            echo "wasm-pack is already installed"
          fi

      - name: Build the project with wasm-pack
        run: wasm-pack build --target bundler

      - name: Upload build artifact
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' || github.event_name == 'pull_request'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ${{ env.BUILD_ARTIFACT_FOLDER }}
          if-no-files-found: "error"
          retention-days: 1

  # Run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable # "stable" sets up the latest stable Rust version

      - name: Cache Cargo registry
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #v5.0.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run unit tests
        run: cargo test

  # Run benchmarks (just to check that they still work)
  bench:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable # "stable" sets up the latest stable Rust version

      - name: Cache Cargo registry
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #v5.0.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run benchmarks
        run: cargo bench

  # Run wasm tests
  wasm-test:
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "${{ env.WASM_TEST_FOLDER }}/package-lock.json"

      - name: Download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ${{ env.BUILD_ARTIFACT_FOLDER }}

      - name: List downloaded artifact files
        run: |
          echo "Contents of ${{ env.BUILD_ARTIFACT_FOLDER }}:"
          ls -R "${{ env.BUILD_ARTIFACT_FOLDER }}"

      - name: Run test for generated wasm files
        run: |
          cd "${{ env.WASM_TEST_FOLDER }}"
          npm ci
          npm run test

  # Deploy to npmjs.com
  publish:
    needs:
      - static-analysis
      - build
      - test
      - wasm-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.ref == 'refs/heads/release'
    concurrency:
      group: publish_npm
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set up Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"

      - name: Download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ${{ env.BUILD_ARTIFACT_FOLDER }}

      - name: List downloaded artifact files
        run: |
          echo "Contents of ${{ env.BUILD_ARTIFACT_FOLDER }}:"
          ls -R "${{ env.BUILD_ARTIFACT_FOLDER }}"

      - name: Publish to npm with provenance attestation
        run: |
          cd "${{ env.BUILD_ARTIFACT_FOLDER }}"
          npm publish